
package tetrisfinal;
import tetrisfinal.renderertetris;
import com.jogamp.opengl.GLCapabilities;
import com.jogamp.opengl.GLEventListener;
import com.jogamp.opengl.GLProfile;
import com.jogamp.opengl.awt.GLCanvas;
import com.jogamp.opengl.util.Animator;
import com.jogamp.opengl.util.FPSAnimator;
/**
 *
 * @author beto1
 */
public class io extends javax.swing.JFrame {

    private renderertetris Renderertetris;
    public static GLCanvas glCanvas;
    
    public io() {
        initComponents();
        Renderertetris = new renderertetris();
        createCanvasJOGL();
    }
    private void createCanvasJOGL() {
        //only three JOGL lines of code ... and here they are
        GLProfile profile = GLProfile.getDefault();
        GLCapabilities glcaps = new GLCapabilities(profile);
        glCanvas = new GLCanvas(glcaps);
        glCanvas.addGLEventListener(Renderertetris);
        glCanvas.addKeyListener(Renderertetris);
        this.panelJOGL.add(glCanvas);
        int w = this.panelJOGL.getWidth();
        int h = this.panelJOGL.getHeight();
        int limx=this.panelJOGL.getX();
        int limy=this.panelJOGL.getY();
//        System.out.println("x " +limx+"y "+limy);
        glCanvas.setSize(w, h);
        glCanvas.setLocation(limx, limy);
        //Instantiating and Initiating Animator 
        final FPSAnimator animator = new FPSAnimator(glCanvas, 100, true);
        animator.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJOGL = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelJOGL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelJOGL.setPreferredSize(new java.awt.Dimension(300, 600));

        javax.swing.GroupLayout panelJOGLLayout = new javax.swing.GroupLayout(panelJOGL);
        panelJOGL.setLayout(panelJOGLLayout);
        panelJOGLLayout.setHorizontalGroup(
            panelJOGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panelJOGLLayout.setVerticalGroup(
            panelJOGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(panelJOGL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(io.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(io.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(io.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(io.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new io().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelJOGL;
    // End of variables declaration//GEN-END:variables
}
